# Generated by Django 4.2.4 on 2023-09-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('amount', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': None,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('indicator', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': None,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'core_sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subsector',
            fields=[
                ('subsector', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': None,
                'managed': False,
            },
        ),
    ]
