# Generated by Django 4.2.4 on 2023-09-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('amount', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': None,
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CountryRating',
        ),
    ]
